# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw2_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(352, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Q1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q1.setGeometry(QtCore.QRect(50, 20, 251, 91))
        self.groupBox_Q1.setObjectName("groupBox_Q1")
        self.ButtonQ1_1 = QtWidgets.QPushButton(self.groupBox_Q1)
        self.ButtonQ1_1.setGeometry(QtCore.QRect(20, 30, 221, 41))
        self.ButtonQ1_1.setObjectName("ButtonQ1_1")
        self.groupBox_Q2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q2.setGeometry(QtCore.QRect(50, 130, 251, 141))
        self.groupBox_Q2.setObjectName("groupBox_Q2")
        self.ButtonQ2_1 = QtWidgets.QPushButton(self.groupBox_Q2)
        self.ButtonQ2_1.setGeometry(QtCore.QRect(20, 30, 221, 41))
        self.ButtonQ2_1.setObjectName("ButtonQ2_1")
        self.ButtonQ2_2 = QtWidgets.QPushButton(self.groupBox_Q2)
        self.ButtonQ2_2.setGeometry(QtCore.QRect(20, 90, 221, 41))
        self.ButtonQ2_2.setObjectName("ButtonQ2_2")
        self.groupBox_Q3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q3.setGeometry(QtCore.QRect(50, 300, 251, 91))
        self.groupBox_Q3.setObjectName("groupBox_Q3")
        self.ButtonQ3_1 = QtWidgets.QPushButton(self.groupBox_Q3)
        self.ButtonQ3_1.setGeometry(QtCore.QRect(20, 30, 221, 41))
        self.ButtonQ3_1.setObjectName("ButtonQ3_1")
        self.groupBox_Q4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q4.setGeometry(QtCore.QRect(50, 410, 251, 141))
        self.groupBox_Q4.setObjectName("groupBox_Q4")
        self.ButtonQ4_1 = QtWidgets.QPushButton(self.groupBox_Q4)
        self.ButtonQ4_1.setGeometry(QtCore.QRect(20, 30, 221, 41))
        self.ButtonQ4_1.setObjectName("ButtonQ4_1")
        self.ButtonQ4_2 = QtWidgets.QPushButton(self.groupBox_Q4)
        self.ButtonQ4_2.setGeometry(QtCore.QRect(20, 90, 221, 41))
        self.ButtonQ4_2.setObjectName("ButtonQ4_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 352, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Q1.setTitle(_translate("MainWindow", "1. Background Subtraction"))
        self.ButtonQ1_1.setText(_translate("MainWindow", "1.1 Background Subtraction"))
        self.groupBox_Q2.setTitle(_translate("MainWindow", "2. Optical Flow"))
        self.ButtonQ2_1.setText(_translate("MainWindow", "2.1 Preprocessing"))
        self.ButtonQ2_2.setText(_translate("MainWindow", "2.2 Video tracking"))
        self.groupBox_Q3.setTitle(_translate("MainWindow", "3. Perspective Transform"))
        self.ButtonQ3_1.setText(_translate("MainWindow", "3.1  Perspective Transform"))
        self.groupBox_Q4.setTitle(_translate("MainWindow", "4. PCA"))
        self.ButtonQ4_1.setText(_translate("MainWindow", "4.1 Image Reconstruction"))
        self.ButtonQ4_2.setText(_translate("MainWindow", "4.2 Compute the reconstruction error"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
